services:
    db_test:
        build:
            # Custom image for file permissions
#            context: ./docker/mysql
            context: ./docker/postgres
            #context: ./docker/mariadb
            args:
                USER_UID: ${USER_UID}
        volumes:
            - "./.data/db_test:/var/lib/mysql"
            - "./docker/mysql/performances.cnf:/etc/mysql/conf.d/performances.cnf"
            - "./.data/pgsql_test:/var/lib/postgresql/data"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}_test
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            # Enable easy switching with Postgres
            PGDATA: /var/lib/postgresql/data
            POSTGRES_USER: ${MYSQL_USER}
            POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
            POSTGRES_DB: ${MYSQL_DATABASE}_test

    db:
        build:
            # Custom image for file permissions
            context: ./docker/mysql
            #context: ./docker/postgres
            #context: ./docker/mariadb
            args:
                USER_UID: ${USER_UID}
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "./docker/mysql/performances.cnf:/etc/mysql/conf.d/performances.cnf"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    app:
        # Need to pass all vars to docker env for Crontab and supervisor scripts
        env_file: "./.env"
        build:
            #context: ./docker/php72-nginx-alpine
            #context: ./docker/php73-nginx-alpine
            #context: ./docker/php74-nginx-alpine
            #context: ./docker/php80-nginx-alpine
            context: ./docker/php81-nginx-alpine
            args:
                USER_UID: ${USER_UID}
        depends_on:
            - db
            - db_test
            - solr
        links:
            - db:db
            - solr:solr
        volumes:
            - ./:/var/www/html
        environment:
            APP_CACHE: ${APP_CACHE}
            TRUSTED_PROXIES: ${TRUSTED_PROXIES}
            USER_UID: ${USER_UID}
            DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}

    mailer:
        image: mailhog/mailhog

    varnish:
        build:
            context: ./docker/varnish
        tmpfs: /usr/local/var/varnish:exec
        depends_on:
            - app
        links:
            - app:app

    solr:
        build:
            # Custom image for file permissions
            context: ./docker/solr
            args:
                USER_UID: ${USER_UID}
        volumes:
            - "./.data/solr:/var/solr"
        environment:
            SOLR_UID: ${USER_UID}
            SOLR_GID: ${USER_UID}
        command:
            - solr-precreate
            - ${SOLR_CORE_NAME}

networks:
    # If you need to use port forwarding, fixing default gateway can be useful
    # to keep same host IP address between service restarts
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/24
