export const DOCUMENT_ENTITY = 'document'
export const NODE_ENTITY = 'node'
export const NODE_TYPE_ENTITY = 'node-type'
export const JOIN_ENTITY = 'join'
export const EXPLORER_PROVIDER_ENTITY = 'explorer-provider'
export const CUSTOM_FORM_ENTITY = 'custom-form'
export const TAG_ENTITY = 'tag'
