/**
 * Nodes Search Widget
 */
export const NODES_SEARCH_REQUEST = 'NODES_SEARCH_REQUEST'
export const NODES_SEARCH_SUCCESS = 'NODES_SEARCH_SUCCESS'
export const NODES_SEARCH_RESET = 'NODES_SEARCH_RESET'
export const NODES_SEARCH_FAILED = 'NODES_SEARCH_FAILED'
export const NODES_SEARCH_ENABLE_FOCUS = 'NODES_SEARCH_ENABLE_FOCUS'
export const NODES_SEARCH_DISABLE_FOCUS = 'NODES_SEARCH_DISABLE_FOCUS'

/**
 * Explorer
 */
export const EXPLORER_REQUEST = 'EXPLORER_REQUEST'
export const EXPLORER_SUCCESS = 'EXPLORER_SUCCESS'
export const EXPLORER_RESET = 'EXPLORER_RESET'
export const EXPLORER_FAILED = 'EXPLORER_FAILED'
export const EXPLORER_OPEN = 'EXPLORER_OPEN'
export const EXPLORER_CLOSE = 'EXPLORER_CLOSE'
export const EXPLORER_LOAD_MORE = 'EXPLORER_LOAD_MORE'
export const EXPLORER_LOAD_MORE_SUCCESS = 'EXPLORER_LOAD_MORE_SUCCESS'
export const EXPLORER_IS_LOADED = 'EXPLORER_IS_LOADED'
export const EXPLORER_UPDATE_SEARCH_TERMS = 'EXPLORER_UPDATE_SEARCH_TERMS'
export const EXPLORER_UPDATE_FILTERS = 'EXPLORER_UPDATE_FILTERS'

/**
 * Filter Explorer
 */
export const FILTER_EXPLORER_OPEN = 'FILTER_EXPLORER_OPEN'
export const FILTER_EXPLORER_CLOSE = 'FILTER_EXPLORER_CLOSE'
export const FILTER_EXPLORER_REQUEST = 'FILTER_EXPLORER_REQUEST'
export const FILTER_EXPLORER_SUCCESS = 'FILTER_EXPLORER_SUCCESS'
export const FILTER_EXPLORER_FAILED = 'FILTER_EXPLORER_FAILED'
export const FILTER_EXPLORER_UPDATE = 'FILTER_EXPLORER_UPDATE'
export const FILTER_EXPLORER_RESET = 'FILTER_EXPLORER_RESET'

/**
 * Keyboard Event
 */
export const KEYBOARD_EVENT_ESCAPE = 'KEYBOARD_EVENT_ESCAPE'
export const KEYBOARD_EVENT_SPACE = 'KEYBOARD_EVENT_SPACE'

/**
 * Login Check
 */
export const LOGIN_CHECK_DISCONNECTED = 'LOGIN_CHECK_DISCONNECTED'

/**
 * Drawers Widget
 */
export const DRAWERS_ADD_INSTANCE = 'DRAWERS_ADD_INSTANCE'
export const DRAWERS_REMOVE_INSTANCE = 'DRAWERS_REMOVE_INSTANCE'
export const DRAWERS_ADD_ITEM = 'DRAWERS_ADD_DOCUMENT'
export const DRAWERS_REMOVE_ITEM = 'DRAWERS_REMOVE_DOCUMENT'
export const DRAWERS_EDIT_INSTANCE = 'DRAWERS_EDIT_INSTANCE'
export const DRAWERS_UPDATE_LIST = 'DRAWERS_UPDATE_LIST'
export const DRAWERS_ENABLE_DROPZONE = 'DRAWERS_ENABLE_DROPZONE'
export const DRAWERS_DISABLE_DROPZONE = 'DRAWERS_DISABLE_DROPZONE'
export const DRAWERS_INIT_DATA_REQUEST = 'DRAWERS_INIT_DATA_REQUEST'
export const DRAWERS_INIT_DATA_REQUEST_SUCCESS = 'DRAWERS_INIT_DATA_REQUEST_SUCCESS'
export const DRAWERS_INIT_DATA_REQUEST_FAILED = 'DRAWERS_INIT_DATA_REQUEST_FAILED'
export const DRAWERS_INIT_DATA_REQUEST_EMPTY = 'DRAWERS_INIT_DATA_REQUEST_EMPTY'

/**
 * Tags
 */
export const TAGS_UPDATE_VALUE = 'TAGS_UPDATE_VALUE'
export const TAGS_REQUEST = 'TAGS_REQUEST'
export const TAGS_REQUEST_SUCCESS = 'TAGS_REQUEST_SUCCESS'
export const TAGS_REQUEST_ERROR = 'TAGS_REQUEST_ERROR'
export const TAG_CREATE_NEW_REQUEST = 'TAG_CREATE_NEW_REQUEST'
export const TAG_CREATE_NEW_REQUEST_SUCCESS = 'TAG_CREATE_NEW_REQUEST_SUCCESS'
export const TAG_CREATE_NEW_REQUEST_ERROR = 'TAG_CREATE_NEW_REQUEST_ERROR'
export const TAG_CREATOR_READY = 'TAG_CREATOR_READY'

/**
 * Document preview widget
 */
export const DOCUMENT_PREVIEW_INIT = 'DOCUMENT_PREVIEW_INIT'
export const DOCUMENT_PREVIEW_DESTROY = 'DOCUMENT_PREVIEW_DESTROY'
export const DOCUMENT_PREVIEW_OPEN = 'DOCUMENT_PREVIEW_OPEN'
export const DOCUMENT_PREVIEW_CLOSE = 'DOCUMENT_PREVIEW_CLOSE'

/**
 * Blanchette Editor widget
 */
export const BLANCHETTE_EDITOR_INIT = 'BLANCHETTE_EDITOR_INIT'
export const BLANCHETTE_EDITOR_IS_LOADING = 'BLANCHETTE_EDITOR_IS_LOADING'
export const BLANCHETTE_EDITOR_LOADED = 'BLANCHETTE_EDITOR_LOADED'
export const BLANCHETTE_EDITOR_ERROR = 'BLANCHETTE_EDITOR_ERROR'
export const BLANCHETTE_EDITOR_SAVE_SUCCESS = 'BLANCHETTE_EDITOR_SAVE_SUCCESS'
