<?php
return array(
    'staticAssets' => array(
        'global' => array(
            'css' => array(
                '/vendor.ce132d7a.css',
                '/style.9b1c51f3.css',
            ),
            'js' => array(
                '/auto-update.f46be045.min.js',
                '/nodeTreeContextActions.dfe4f69e.min.js',
                '/documentsBulk.071a5194.min.js',
                '/nodesBulk.0556aa66.min.js',
                '/tagsBulk.db6c37be.min.js',
                '/documentsList.d199c740.min.js',
                '/documentWidget.cc82c91d.min.js',
                '/documentUploader.9543ad6f.min.js',
                '/documentExplorer.e3487891.min.js',
                '/folderExplorer.013a7924.min.js',
                '/nodeWidget.4cec2410.min.js',
                '/nodeExplorer.f4ec9074.min.js',
                '/nodeEditSource.6e212173.min.js',
                '/customFormWidget.b9782b55.min.js',
                '/saveButtons.1f1fcdc2.min.js',
                '/settingsSaveButtons.2629f847.min.js',
                '/nodeTree.53dfa2f9.min.js',
                '/nodeStatuses.58735baf.min.js',
                '/geotagField.e0f848d1.min.js',
                '/multiGeotagField.8a097b93.min.js',
                '/childrenNodesField.6b9815ab.min.js',
                '/markdownEditor.5be2c40e.min.js',
                '/jsonEditor.d7a1d073.min.js',
                '/cssEditor.8f0fa164.min.js',
                '/yamlEditor.f574a221.min.js',
                '/tagAutocomplete.f319ceeb.min.js',
                '/folderAutocomplete.8ed136e2.min.js',
                '/inputLengthWatcher.a3c1612e.min.js',
                '/stackNodeTree.135c2fd7.min.js',
                '/nodeTypeFieldsPosition.3fb708c9.min.js',
                '/nodeTypeFieldEdit.a5bd45d2.min.js',
                '/customFormFieldsPosition.c4cd285a.min.js',
                '/customFormFieldEdit.bfc96f6b.min.js',
                '/entriesPanel.8c8df14c.min.js',
                '/import.2fb2dc82.min.js',
                '/rozierMobile.02f53ed9.min.js',
                '/lazyload.4372e462.min.js',
                '/plugins.c220a134.min.js',
                '/main.f1cf6020.min.js',
                '/uikit.16c31cc8.min.js',
                '/sortable.fa438a02.min.js',
                '/datepicker.6d1d4ea6.min.js',
                '/nestable.b2c8035c.min.js',
                '/pagination.7549bbd0.min.js',
                '/notify.135043d7.min.js',
                '/tooltip.98f5d7fe.min.js',
                '/TweenMax.5e6c8305.min.js',
                '/ScrollToPlugin.aad35ce7.min.js',
                '/bootstrap-switch.0e52ba1d.min.js',
                '/jquery.minicolors.330af846.min.js',
                '/mousetrap.0faa7fc5.min.js',
                '/codemirror.249c65b4.min.js',
                '/markdown.dcf50a24.min.js',
                '/javascript.0f2c135f.min.js',
                '/css.be29c838.min.js',
                '/overlay.7abff7c5.min.js',
                '/xml.d8d78485.min.js',
                '/yaml.37ccd74e.min.js',
                '/gfm.f8f2bbcd.min.js',
                '/markdown-it.b53892f9.min.js',
                '/markdown-it-footnote.99ed344d.min.js',
                '/dropzone.0885a777.min.js',
                '/heartcode-canvasloader.9acb6af4.min.js',
                '/jquery.actual.031b425d.min.js',
                '/jquery.caret.c9cf9c9e.min.js',
                '/jquery.tag-editor.bc1ee437.min.js',
            ),
        ),
        'simple' => array(
            'css' => array(
            ),
            'js' => array(
                '/rozier-backend-theme-simple.a141d9b8.min.js',
            ),
        ),
        'custom-forms' => array(
            'css' => array(
                '/vendor.ce132d7a.css',
                '/custom-forms-front.176c7ebe.css',
            ),
            'js' => array(
                '/rozier-backend-theme-cforms.48af2ad4.min.js',
            ),
        ),
    )
);
