<?php
declare(strict_types=1);

namespace RZ\Roadiz\Console;

use RZ\Roadiz\Core\Kernel;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Command line utils for installing RZ-CMS v3 from terminal.
 */
class HtaccessCommand extends Command
{
    protected function configure()
    {
        $this
            ->setName('generate:htaccess')
            ->setDescription('Generate .htaccess <info>(Apache v2.4)</info> files to protect directories and redirect trafic to index.php.');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|null|void
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);
        /** @var Kernel $kernel */
        $kernel = $this->getHelper('kernel')->getKernel();
        $fs = new Filesystem();
        $io->note('Generating .htaccess files to protect folders.');

        // Simple deny access files
        $outputs = $this->protectFolders([
            "/app/conf",
            "/conf",
            "/src",
            "/samples",
            "/gen-src",
            "/app/gen-src",
            "/files/fonts",
            "/files/private",
            "/bin",
            "/tests",
            "/cache",
            "/logs",
            "/app/cache",
            "/app/logs",
        ]);


        /*
         * Protect root
         */
        $filePath = $kernel->getPublicDir() . "/.htaccess";
        if ($fs->exists($kernel->getPublicDir()) && !$fs->exists($filePath)) {
            file_put_contents($filePath, $this->getMainHtaccessContent() . PHP_EOL);
            $outputs[] = $filePath;
        } else {
            $outputs[] = '<error>Can’t write ' . $filePath . ', file already exists or folder is absent.</error>';
        }

        /*
         * Protect themes
         */
        $filePath = $kernel->getPublicDir() . "/themes/.htaccess";
        if ($fs->exists($kernel->getPublicDir() . "/themes") && !$fs->exists($filePath)) {
            file_put_contents($filePath, $this->getThemesHtaccessContent() . PHP_EOL);
            $outputs[] = $filePath . PHP_EOL;
        } else {
            $outputs[] = '<error>Can’t write ' . $filePath . ', file already exists or folder is absent.</error>';
        }

        $io->listing($outputs);
        return 0;
    }

    protected function protectFolders(array $paths): array
    {
        $outputs = [];
        /** @var Kernel $kernel */
        $kernel = $this->getHelper('kernel')->getKernel();
        $fs = new Filesystem();
        foreach ($paths as $path) {
            $filePath = $kernel->getProjectDir() . $path . "/.htaccess";
            if ($fs->exists($kernel->getProjectDir() . $path) &&  !$fs->exists($filePath)) {
                file_put_contents($filePath, "deny from all" . PHP_EOL);
                $outputs[] = $filePath;
            } else {
                $outputs[] = '<error>Can’t write ' . $filePath . ", file already exists or folder is absent.</error>";
            }
        }
        return $outputs;
    }

    protected function getMainHtaccessContent()
    {
        return <<<EOT
# ------------------------------------
# Automatic Apache 2.4 .htaccess file
# Generated by Roadiz
# ------------------------------------
IndexIgnore *

# ------------------------------------
# EXPIRES CACHING
# ------------------------------------
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/webp "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/pdf "access plus 1 month"
    ExpiresByType text/x-javascript "access plus 1 month"
    ExpiresByType text/javascript "access plus 1 month"
    ExpiresByType application/x-shockwave-flash "access plus 1 month"
    ExpiresByType image/x-icon "access plus 1 year"
    ExpiresDefault "access plus 2 days"
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
    # Redirect to www
    #RewriteCond %{HTTP_HOST} !^www\.
    #RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
EOT;
    }

    protected function getThemesHtaccessContent()
    {
        return <<<EOT
# ------------------------------------
# Automatic Apache 2.4 .htaccess file
# Generated by Roadiz
# ------------------------------------
<Files ~ "^\.php|yml|twig|xlf|rzn|rzt|rzg">
    # Apache 2.2 configuration:
    #Order allow,deny
    #Deny from all

    # Apache 2.4 configuration:
    Require all denied
</Files>
EOT;
    }
}
